[package]
name = "starfall-api"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.28"
lune = "0.8.3"
once_cell = "1.19.0"
rbx_types = "1.8.0"
regex = "1.10.4"
reqwest = "0.12.3"
rocket = "0.5.0"
serde_json = "1.0.116"
